### ISSUE TITLE
Getting frontend error when deploying behind reverse proxy TypeError: Cannot read properties of undefined (reading '_s')

### ISSUE THREAD

**Issue by dfoxg** [InvoiceShelf/InvoiceShelf#149]
**Describe the bug**
When i use the default docker-compose file with mysql i get a error in the browser console:

```
VM591 main-qwbh3PkU.js:15 TypeError: Cannot read properties of undefined (reading '_s')
    at r (main-qwbh3PkU.js:31:3726)
    at ft (main-qwbh3PkU.js:31:5825)
    at setup (NotificationRoot-Bt829cge.js:1:3092)
    at Jo (VM591 main-qwbh3PkU.js:15:1344)
    at F5 (VM591 main-qwbh3PkU.js:15:57350)
    at CP (VM591 main-qwbh3PkU.js:15:57133)
    at Ce (VM591 main-qwbh3PkU.js:15:35396)
    at ie (VM591 main-qwbh3PkU.js:15:35276)
    at y (VM591 main-qwbh3PkU.js:15:31991)
    at j (VM591 main-qwbh3PkU.js:15:33503)
```

This happens right after startup, so i dont even get to the installation step

**Expected behavior**

Im using following configs:

<details><summary>docker-compose</summary>
<p>

```
#-------------------------------------------
# InvoiceShelf SQLite docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  invoiceshelf_db:
    container_name: invoiceshelf_db
    image: mariadb:11.5
    environment:
      - MYSQL_ROOT_PASSWORD=invoiceshelf_admin
      - MYSQL_DATABASE=invoiceshelf
      - MYSQL_USER=invoiceshelf
      - MYSQL_PASSWORD=invoiceshelf
    expose:
      - 3306
    volumes:
      - /opt/invoiceshelf/conf:/var/lib/mysql
    networks:
      - invoiceshelf
    restart: unless-stopped

  invoiceshelf:
    image: invoiceshelf/invoiceshelf:2.0.0-RC1
    container_name: invoiceshelf
    ports:
      - 127.0.0.1:4412:80
    volumes:
      - /opt/invoiceshelf/data:/data
    environment:
      - PHP_TZ=Europe/Berlin
      - TIMEZONE=Europe/Berlin
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://invoiceshelf.trusted.home
      - DB_CONNECTION=mysql
      - DB_HOST=invoiceshelf_db
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=invoiceshelf
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=invoiceshelf.trusted.home
      - SANCTUM_STATEFUL_DOMAINS=invoiceshelf.trusted.home
      - STARTUP_DELAY=30
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped
    depends_on:
      - invoiceshelf_db

networks:
  invoiceshelf:

```

</p>
</details> 

<details><summary>nginx config</summary>
<p>

```
server {
  listen {{ ansible_host }}:443 ssl;

  ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
  ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

  server_name invoiceshelf.home;
  return 301 $scheme://invoiceshelf.trusted.home$request_uri;
}

server {
    listen {{ ansible_host }}:443 ssl;
    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
    server_name invoiceshelf.trusted.home;

    location / {
        proxy_pass http://127.0.0.1:4412;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        add_header Content-Security-Policy "upgrade-insecure-requests;";
    }
}
```

</p>
</details> 

**Screenshots**

**Please complete the following information:**
- InvoiceShelf version: 2.0.0-RC1 (docker)
- Database type and version: 11.5

**Optional info**
- OS:  Windows 11
- Browser: Brave
