### ISSUE TITLE
Mixed Content HTTPS error

### ISSUE THREAD

**Issue by MrToast72** [InvoiceShelf/InvoiceShelf#230]
### Issue filing pre-requisites

- [X] I've checked the documentation.
- [X] I've looked for similar issues both Open and Closed.
- [X] Ive tried clearing both cache and cookies in my browser or tried opening the app in the Incognito/InPrivate window.

### Describe the bug

So I have an odd error when trying to login to my invoiceshelf setup. Simply put, if I put in my credentials and click login, I get an error :

`Please check your internet connection or wait until servers are back online.`

Checking the browser console I see this :

`
Mixed Content: The page at 'https://invoice.mydomain.com/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://invoice.mydomain.com/admin/dashboard'. This request has been blocked; the content must be served over HTTPS.
`

But if I just refresh the page, it will redirect me to my invoice.mydomain.com/admin/dashboard

I run Nginx Proxy Manager as a separate container to manage all my proxying, so best I can do is provide a screenshot of that :

<img width="500" alt="Screenshot 2024-11-20 at 09 35 46" src="https://github.com/user-attachments/assets/6576046e-830c-469c-ab03-fc563c07f0b4">
<img width="499" alt="Screenshot 2024-11-25 at 10 04 28" src="https://github.com/user-attachments/assets/61d59be4-647f-4b89-874b-9d5be410025c">

For Nginx I have tried both http and https scheme, force SSL, and adding things found in other bug reports here to the advanced section (however most of those dont work as they are blocked by Nginx Proxy Manager, and would require adding a new mounted file to the container with the custom config. This wouldnt make sense as I have all my other apps being served on http with force SSL on.) turning on force SSL, or https scheme gives me different errors to which the site won't load at all, either a 500 error or a cloud flare endpoint error. 

As well as a picture of the error its self :

<img width="1728" alt="Screenshot 2024-11-20 at 09 28 20" src="https://github.com/user-attachments/assets/4b2c8e7a-72be-4cc4-93fb-13de188a51a2">

and of course my docker compose file :

```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:2.0.0
    container_name: invoiceshelf
    ports:
      - 6942:80
    volumes:
      - /NVMe-Pool/App-Data-Pool/invoiceshelf/data:/data
      - /NVMe-Pool/App-Data-Pool/invoiceshelf/conf:/conf
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=America/REDACTED
      - TIMEZONE=America/REDACTED
      - APP_NAME=Laravel
      - APP_ENV=production   # Changed to production to see if that helped at all
      - APP_DEBUG=true
      - APP_FORCE_HTTPS=true   # Added to test and see if another users comment would help
      - APP_URL=https://invoice.mydomain.com/
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=true   # Changing this does nothing 
      - SESSION_SECURE_COOKIE=true   # Added because of another users comment to see if it would help
      - SESSION_PATH=/
      - SESSION_DOMAIN=invoice.mydomain.com
      - SANCTUM_STATEFUL_DOMAINS=invoice.mydomain.com
      - STARTUP_DELAY=
    restart: unless-stopped

networks:
  invoiceshelf:
```

Changing the APP_URL between http and https changes nothing, and so far all the "fixes" people listed didn't help me. The issue I found [here](https://github.com/InvoiceShelf/InvoiceShelf/issues/33), which is the exact same as mine, didn't help either, the user fixed their problem by applying some settings to their nginx setup, however this did not help my setup. So im not sure where to go from here, any help is appreciated!

### Steps to Reproduce the issue

1. Try to login after creating new docker container and following all the necessary steps
2. Recive the above errors mentioned. Checking browser console also shows an error as stated above.

### Expected behavior

Logging in would direct me to the dashboard over https instead of http

### Actual behavior

Error is returned in console :
`
Mixed Content: The page at 'https://invoice.mydomain.com/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://invoice.mydomain.com/admin/dashboard'. This request has been blocked; the content must be served over HTTPS.
`

### InvoiceShelf version

v2.0.0

### PHP version

v8.2.24

### Database type

SQLite

### Database version

v3.40.1

### Web Browser

Brave & Safari

### Server OS

Debian GNU/Linux 11 (bullseye) x86_64

### Reverse-proxy logs

```irc logs
2024/11/25 16:23:25 [warn] 1994#1994: *14 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 172.71.147.106, server: invoice.mydomain.com, request: "GET /build/assets/main-WS8l16KQ.js HTTP/1.1", upstream: "http://10.0.72.27:6942/build/assets/main-WS8l16KQ.js", host: "invoice.mydomain.com", referrer: "https://invoice.mydomain.com/login"
2024/11/25 16:23:26 [warn] 1993#1993: *27 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.71.147.195, server: invoice.mydomain.com, request: "GET /build/assets/Poppins-Medium-DwAlJ_UI.ttf HTTP/1.1", upstream: "http://10.0.72.27:6942/build/assets/Poppins-Medium-DwAlJ_UI.ttf", host: "invoice.mydomain.com", referrer: "https://invoice.mydomain.com/build/assets/main-C4n-zHjJ.css"
```
