### ISSUE TITLE
i18n string not parsing correctly

### ISSUE THREAD

**Issue by AkashRajpurohit** [InvoiceShelf/InvoiceShelf#260]
### Issue filing pre-requisites

- [X] I've checked the documentation.
- [X] I've looked for similar issues both Open and Closed.
- [X] Ive tried clearing both cache and cookies in my browser or tried opening the app in the Incognito/InPrivate window.

### Describe the bug

While self-hosting invoiceshelf, noticed that at most of the places the i18n string is not parsed correctly, not a blocker but feels weird pretty much everywhere.

Example:
<img width="824" alt="image" src="https://github.com/user-attachments/assets/afc45e6c-2258-4c2a-9b2c-7bbe46574fb2" />
<img width="481" alt="image" src="https://github.com/user-attachments/assets/64772fa0-9f51-4a43-8825-f5cd5d0869d5" />

### Steps to Reproduce the issue

Run instance of invoiceshelf via docker, here's my docker-compose.yml file

```yaml
services:
  invoiceshelf:
    image: "invoiceshelf/invoiceshelf:latest"
    container_name: "invoiceshelf"
    volumes:
      - "./config:/conf"
      - "./data:/data"
    ports:
      - "27725:80"
    environment:
      - PGID=1000
      - PUID=1000
      - PHP_TZ=Asia/Kolkata
      - TIMEZONE=Asia/Kolkata
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://invoice.domain.com
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=invoice.domain.com
      - SANCTUM_STATEFUL_DOMAINS=invoice.domain.com
      - STARTUP_DELAY=
    restart: unless-stopped
```

### Expected behavior

String should show up correctly.

### Actual behavior

String is showing up as i18n key and not the correct value.

### InvoiceShelf version

2.0.0

### PHP version

N.A

### Database type

SQLite

### Database version

N.A
