### ISSUE TITLE
access custom invoice fields in the invoice PDF template

### ISSUE THREAD

**Issue by accumulator** [InvoiceShelf/InvoiceShelf#326]
### What feature or improvement do you think would benefit InvoiceShelf?

I want to reference a custom invoice field in the PDF template generation, but custom fields can only be included in compound text blocks like billing address.

### Requirements

expose the invoice custom fields in the $invoice variable

### App Version

2.1.1

**Comment by rihards-simanovics** [comment]
Hey @accumulator, I'm not sure if you are part of the InvoiceShelf Discord Server yet, but I did post a code snippet that you could use in the Invoice PDF blades to do that. It's not official, but I'm waiting for a response from @gdarko or @mchev if there is a better way to do it.

Here is the snippet in case you are interested:
```blade
<!DOCTYPE html>
<html>
@php
    function getCustomFieldValue($model, $slug) {
        // Iterate through the fields collection
        foreach ($model->fields as $field) {
            // Check if the slug matches
            if ($field->customField->slug === $slug) {
                // Return the string_answer
                return $field->string_answer;
            }
        }
        // Return null or a default value if not found
        return null;
    }
@endphp

<head>
  ...
</head>

...

<body>
  ...
  <p>somewhere in your template inside the body tag</p>
  {{ getCustomFieldValue($invoice, 'CUSTOM_FIELD_SLUG') }}
  {{ getCustomFieldValue($invoice->customer, 'CUSTOM_CUSTOMER_FIELD_SLUG') }}
  ...
  </body>
</html>
```

hope this helps.

# [UPDATE] [This snippet is now only updated in the wiki workarounds section](https://github.com/InvoiceShelf/InvoiceShelf/wiki/Workarounds#2-access-custom-fields-inside-the-invoice-blade-template)

**Comment by Neilisin** [comment]
Thanks for this contribution, and thanks for updating the wiki. 

I am currently going through the process of designing an invoice template, and finding the documentation is in much need of love.  Which is good news, as I'd love to contribute and pitch in for adding to the documentation.

**Comment by kinslayer1982** [comment]
Is this supposed to work in the current 2.2.0-alpha1 ? I'm running this nightly release in docker and it does not seem to do anything. I tried changing the return value but all I see is an empty spot in the final invoice. If I for example put `The current UNIX timestamp is {{ time() }}.` in my template, I can see the timestamp in the final invoice.

Just to make sure: If I have a custom field that is being displayed as `CUSTOM_INVOICE_FROM` in the custom field overview, then I would use `{{ getCustomFieldValue($invoice, 'CUSTOM_INVOICE_FROM') }}` in the template, correct?

**Comment by rihards-simanovics** [comment]
> Is this supposed to work in the current 2.2.0-alpha1 ? I'm running this nightly release in docker and it does not seem to do anything.

I will admit I haven't tested, but will some time tomorrow.

> Just to make sure: If I have a custom field that is being displayed as `CUSTOM_INVOICE_FROM` in the custom field overview, then I would use `{{ getCustomFieldValue($invoice, 'CUSTOM_INVOICE_FROM') }}` in the template, correct?

It also depends on the model in which you store the field.

**Comment by kinslayer1982** [comment]
> > Is this supposed to work in the current 2.2.0-alpha1 ? I'm running this nightly release in docker and it does not seem to do anything.
> 
> I will admit I haven't tested, but will some time tomorrow.

That would be really great.

> > Just to make sure: If I have a custom field that is being displayed as `CUSTOM_INVOICE_FROM` in the custom field overview, then I would use `{{ getCustomFieldValue($invoice, 'CUSTOM_INVOICE_FROM') }}` in the template, correct?
> 
> It also depends on the model in which you store the field.

Yes, I forgot to mention. I set model:invoice on the custom field and am trying to use it in an invoice template.

**Comment by rihards-simanovics** [comment]
I've just recorded a tutorial on how to access the fields:

[posted it on YouTube <img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/00860ac0-d100-474b-a86e-a5433941fa39" />](https://www.youtube.com/watch?v=ayAkey4mJm4)

**Comment by rihards-simanovics** [comment]
@kinslayer1982 workaround still works on 2.2.0-alpha, please see the video above for more details.

**Comment by kinslayer1982** [comment]
Wow, really appreciate your effort with the video. Unfortunately this doesn't help me. That's exactly what I did, but I still don't see the custom field value on my invoice. Just tested again and it works if I create a custom text field, but what I tried to use was a date field as my wife's company does not sell items, they provide services. So I wanted to use a 'from' field and a 'till' field. And these don't turn up at all.

Regarding the mysql error message: it does impact the app. I created an issue in the docker section, see [#58](https://github.com/InvoiceShelf/docker/issues/58).

Edit: `dd()` does not work for me on nightly. What works to get some output is `print_r()`.

**Comment by rihards-simanovics** [comment]
> Wow, really appreciate your effort with the video. Unfortunately this doesn't help me. That's exactly what I did, but I still don't see the custom field value on my invoice. Just tested again and it works if I create a custom text field, but what I tried to use was a date field as my wife's company does not sell items, they provide services. So I wanted to use a 'from' field and a 'till' field. And these don't turn up at all.
> 
> Regarding the mysql error message: it does impact the app. I created an issue in the docker section, see [#58](https://github.com/InvoiceShelf/docker/issues/58).
> 
> Edit: `dd()` does not work for me on nightly. What works to get some output is `print_r()`.

dd() doesn't work 🤨?

Something is wrong. Please check your environment. I was running inside Docker, so I'm not familiar with your setup. However, please verify that you have everything and that you are editing the correct invoice template.

Another possibility I can think of is that the field has a custom value type or some kind of caching. Try a local development environment.

**Comment by kinslayer1982** [comment]
I'm using the 2.2.0-alpha1 with the provided docker-compose file. Only changes are the domain/URL variables. I'm editing invoice4.blade.php and using invoice4 template.

The fields are set to type date from the dropdown.

Edit: `dd(`) works on the sqlite version without reverse proxy. Might be related to that. The other instance I plan to use is the postrgres version behind nginx reverse proxy.

**Comment by rihards-simanovics** [comment]
> I'm using the 2.2.0-alpha1 with the provided docker-compose file. Only changes are the domain/URL variables. I'm editing invoice4.blade.php and using invoice4 template.

Just make sure it's a generated template using the `php artisan make:template [template_name]` command; otherwise, on restart, it'll be gone.

> The fields are set to type date from the dropdown.

I'll play around with it today and see if there is a difference in how those values are displayed; perhaps you need a different attribute for those.

> Edit: `dd(`) works on the sqlite version without reverse proxy. Might be related to that. The other instance I plan to use is the postrgres version behind nginx reverse proxy.

A reverse proxy and database type wouldn't usually play a role. What would play a role is the use of the `APP_DEBUG` and `APP_ENV` env variables. If `APP_DEBUG` is set to "true", `dd()` should work; you may also need to set `APP_ENV` to "development" instead of "production", as some features may be disabled in production.

**Comment by kinslayer1982** [comment]
Ok, just wanted to make sure I don't forget something important.

Invoice4 is my generated template inside templates/pdf/invoice folder.

Both are set to `production` and and `debug: false`.

**Comment by Neilisin** [comment]
Hello all, I've managed to implement everything fairly well before the video came out, the custom fields worked a treat.  Thanks for this, although. admittedly it's a bit messy, having to pull the file from docker to the main host, and then bringing the code to my regular editor;  and back again was a mare!  However, I'd love to be part of the conversation in improving this experience.   I also am at the stage of playing css layout which comply with domtopdf.   I'm sure we could do this a better way.

**Comment by rihards-simanovics** [comment]
> Ok, just wanted to make sure I don't forget something important.
> 
> Invoice4 is my generated template inside templates/pdf/invoice folder.

Yes, so that's good, so if you generate it, then you're good to go.

> Both are set to `production` and and `debug: false`.

And yes, in here you need to set to `development` and `true` so the app can use the debugging functions. Or at least that's my assumption, as I would imagine Laravel Framework needing those to be set like that to use `dd()`.

**Comment by kinslayer1982** [comment]
@Neilisin Getting the file for editing and putting it back really comes down to your specific setup. For me it's a matter of 2-3 seconds.
But as this is only a workaround for now it's okay I think.

@rihards-simanovics No. Both my instances use the same settings aside from 1 being sqlite and 1 postgres. And it works on one but not on the other.

**Comment by rihards-simanovics** [comment]
To be fully transparent, my instance is MySQL, but I really don't see why it would be having issues under one DB and not the other.  Remember, all the difference really is that the compose file contains an extra image for either MySQL or PostgreSQL. SQLite simply stores a DB file inside the storage.

@kinslayer1982, the only thing I can see that could be causing this is the above-mentioned app env vars. Can you please share the compose files for both so I can see the difference between he two? Feel free to redact any passwords you may have there.

**Comment by kinslayer1982** [comment]
Sure, here you go:

```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:nightly
    container_name: invoiceshelf
    ports:
      - "8090:8080" # 8090 is the public port.
    volumes:
      - /volume2/docker/data/invoiceshelf/storage:/var/www/html/storage
      - /volume2/docker/data/invoiceshelf/bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://invoice.sammael.de
      - ASSET_URL=https://invoice.sammael.de
      - DB_CONNECTION=pgsql
      - DB_HOST=192.162.172.31
      - DB_PORT=3409
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=XXX
      - DB_PASSWORD_FILE=
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=240
      - SESSION_DOMAIN=invoice.sammael.de
      - SANCTUM_STATEFUL_DOMAINS=invoice.sammael.de
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped
```

```
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:nightly
    container_name: invoiceshelf
    ports:
      - "8090:8080" # 8090 is the public port.
    volumes:
      - /var/docker_data/invoiceshelf/storage:/var/www/html/storage
      - /var/docker_data/invoiceshelf/bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://192.162.172.90:8090
      - ASSET_URL=http://192.162.172.90:8090
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/storage/app/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=240
      - SESSION_DOMAIN=192.162.172.90
      - SANCTUM_STATEFUL_DOMAINS=192.162.172.90:8090
      #- MAIL_DRIVER=smtp
      #- MAIL_HOST=smtp.mailtrap.io
      #- MAIL_PORT=2525
      #- MAIL_USERNAME=null
      #- MAIL_PASSWORD=null
      #- MAIL_PASSWORD_FILE=<filename>
      #- MAIL_ENCRYPTION=null
    restart: unless-stopped
```
