### ISSUE TITLE
TypeError: l is undefined; Docker installation behind nginx reverse proxy

### ISSUE THREAD

**Issue by vincurekf** [InvoiceShelf/InvoiceShelf#396]
### Issue filing prerequisites

- [x] I've checked the [documentation](https://docs.invoiceshelf.com/).
- [x] I've looked for similar issues both Open and Closed.
- [x] I've tried clearing both cache and cookies in my browser or tried opening the app in the Incognito/InPrivate window.

### Describe the bug

When accessing the docker installation via external URL I am getting:
```
TypeError: l is undefined
```
Login form is not rendered:
![Image](https://github.com/user-attachments/assets/585e3b2c-35d2-4063-b728-bf5480c7b4e1)

Issue is on this line:
![Image](https://github.com/user-attachments/assets/87dd8fd1-bfaa-41a4-aa85-8feb07111531)

## Does not work:
1. Create new docker installation
2. Running behind nginx proxy - domain pointing with Cloudflare + Cloudflare SSL certificate
3. Visit domain url

## Does work
Accessing the same installation on the local server IP works and the login form is rendered.
(Although I get the CSRF token mismatch, but in a weird way I get notified that Logging in was successfull, then I get error Unauthenticated then I get CSRF error - but that is not the issue here)
![Image](https://github.com/user-attachments/assets/25b1a5ea-8519-42e0-ba64-6d1e064d3323)

### Expected behaviour

Login form should at least be rendered, preferably working.

### Actual behaviour

Login form is not rendered.

### Docker

- [x] App running in Docker Container.
- [x] Docker container running behind Reverse proxy.

### InvoiceShelf version

v2.1.1

### PHP version

v8.2

### Database type

SQLite

### Database version

sqlite3

### Web Browser

Firefox

### Server OS

Linux

### Reverse-proxy logs

```irc logs

```

### Laravel/PHP logs

```irc logs

```

**Comment by rihards-simanovics** [comment]
Hey @vincurekf, since you're using Docker and IS is behind a reverse proxy, I have a couple of follow-ups:

1. Can you please post your reverse proxy configs (feel free to redact any sensitive details)
2. Can you post the contents of your `docker-compose.yml` file (again, feel free to redact the keys/passwords and other sensitive details, but for domains keep this format `sub.acme.com:port/path`)
3. Is the InvoiceShelf container set to the `latest` or `nightly` builds?

**Comment by rihards-simanovics** [comment]
Also, the most common issue with CSRF is incorrectly set ENV VARS in the docker-compose.yaml file. Please make sure that all of the values you entered during the setup process of the IS are present in the env vars, pay close attention to:
1. `APP_URL` - URL format `http(s)://(sub.)acme.com(:port)`,
2. `SESSION_DOMAIN` - FQDN format `domain.com`, and
3. `SANCTUM_STATEFUL_DOMAINS` - list of FQDN + PORT (opt) `acme.com(:port),(sub.)acme.com`

**Comment by vincurekf** [comment]
Hi @rihards-simanovics , I am running 2.1.1 version now, but the same issue was on nightly build.
my.domain.com was also set in the initial webui configuration steps. 

Here are my configs:

nginx.conf
```nginx
server {
    server_name my.domain.com;

    # set timeout
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    send_timeout       600s;

    location / {
        proxy_pass http://localhost:9090;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        add_header Content-Security-Policy "upgrade-insecure-requests;";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header X-XSS-Protection "1; mode=block";
        add_header Referrer-Policy no-referrer;
    }
}
```

docker-compose.yml:
```yaml
#-------------------------------------------
# InvoiceShelf SQLite docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:2.1.1
    container_name: invoiceshelf
    ports:
      - 9090:80
    volumes:
      - ./invoiceshelf_sqlite/data:/data
      - ./invoiceshelf_sqlite/conf:/conf
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=UTC
      - TIMEZONE=Europe/Prague
      - APP_NAME=InvoiceShelf
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://my.domain.com
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite # please don't touch this!
      - CACHE_STORE=file
      - SESSION_DRIVER=cookie
      - SESSION_LIFETIME=3600
      - SESSION_ENCRYPT=true
      - SESSION_PATH=/
      - SESSION_DOMAIN=my.domain.com
      - SANCTUM_STATEFUL_DOMAINS=my.domain.com
      - STARTUP_DELAY=
      - MAIL_DRIVER=smtp
      - MAIL_HOST=***
      - MAIL_PORT=***
      - MAIL_USERNAME=***
      - MAIL_PASSWORD=***
      - MAIL_ENCRYPTION=***
    restart: unless-stopped

networks:
  invoiceshelf:
```

The generated `invoiceshelf_sqlite/conf/.env` seem to match:
```env
APP_ENV=production
APP_KEY=***
APP_DEBUG=false
APP_NAME=InvoiceShelf
APP_LOG_LEVEL=debug
APP_TIMEZONE=UTC
APP_URL=https://my.domain.com

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file
APP_MAINTENANCE_STORE=database

BCRYPT_ROUNDS=12

DB_CONNECTION=sqlite
DB_HOST=
DB_PORT=
DB_DATABASE=/var/www/html/InvoiceShelf/database/database.sqlite
DB_USERNAME=
DB_PASSWORD=

BROADCAST_CONNECTION=log
CACHE_STORE=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=cookie
SESSION_LIFETIME=3600
SESSION_ENCRYPT=true
SESSION_PATH=/
SESSION_DOMAIN=my.domain.com

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=***
MAIL_PORT=***
MAIL_USERNAME=***
MAIL_PASSWORD=***
MAIL_ENCRYPTION=***

MAIL_FROM_NAME="***"
MAIL_FROM_ADDRESS=***

PUSHER_APP_ID=
PUSHER_KEY=
PUSHER_SECRET=

SANCTUM_STATEFUL_DOMAINS=my.domain.com
TRUSTED_PROXIES="*"

CRON_JOB_AUTH_TOKEN=""
LOG_STACK=single

PDF_DRIVER=dompdf
GOTENBERG_HOST=
GOTENBERG_PAPERSIZE=
TIMEZONE=Europe/Prague
```

laravel. log is empty:
![Image](https://github.com/user-attachments/assets/4f2c4e97-e5dc-48dc-80d4-febe0f11175e)
