### ISSUE TITLE
[Bug] Creating Backups fails

### ISSUE THREAD

**Issue by Dschogo** [InvoiceShelf/InvoiceShelf#42]
**Describe the bug**
Creating a backup results in an error `Undefiend constant: Spatie\Backup\Tasks\Backup\SIGINT`.

![image](https://github.com/InvoiceShelf/InvoiceShelf/assets/36862419/0088091a-7dbf-49d1-b023-d444639270a6)

local_public / local_private nor backup type changes this behavior.

**Expected behavior**
Create a backup without error.

**Additional info**
How should a backup be restored? Didn't see anything during setup/menu option. Enter docker (for me) and execute restore directly on the database via cli?

**Please complete the following information:**
- InvoiceShelf version: docker-compose (invoiceshelf/invoiceshelf:latest) - 1.1.0
- PHP version: bundled
- Database type and version: bundled

**Optional info**
- OS:  docker host: debian arm64
- Browser: Firefox

<details>
  <summary>docker-compose.yml</summary>

  ```yml
#-------------------------------------------
#  Docker Compose
#  - Darko Gjorgjijoski
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

version: '3'

services:
  invoiceshelf_db:
    container_name: invoiceshelf_db
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=randompw
      - MYSQL_DATABASE=invoiceshelf
      - MYSQL_USER=invoiceshelf
      - MYSQL_PASSWORD=randompw
    expose: 
      - 3306
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - invoiceshelf
    restart: unless-stopped

  invoiceshelf:
    image: invoiceshelf/invoiceshelf
    container_name: invoiceshelf
    ports:
      - 90:80
    volumes:
      - ./invoiceshelf/data:/data
    networks:
      - invoiceshelf
    environment:
      - PUID=1000
      - PGID=1000
      - USER=invoiceshelf
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - DB_CONNECTION=mysql
      - DB_HOST=invoiceshelf_db
      - DB_PORT=3306
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=randompw
      - STARTUP_DELAY=0
    restart: unless-stopped
    depends_on:
      - invoiceshelf_db

networks:
  invoiceshelf:

volumes:
  mysql:
  ```
</details>
